# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: HipHop_&_Coder
subtitle: 事在人为，功不唐捐！
description: 喜欢HipHop的程序猿！
keywords:  HipHop Coder Keep Real
author: 卡尔西 
language: zh-CN 
timezone: Asia/ShangHai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.hiphopcoder.com
# permalink: :year/:month/:day/:title/
permalink: :year/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: truurl_fore
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page:
  yearly: true
  monthly: true

tag_generator:
  per_page:


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Landscape-X 


### Them  e Config
## Heade  r
menu:
  home: /
  archive: /archives
  user: /about.html

mobile_menu:
  home: /
  archive: /archives
  user: /about.html

rss: /atom.xml

## Content
excerpt_link: Read More
fancybox: true
mathjax: true


## Sidebar
sidebar: right
widgets:
- recent_posts
- category
# - tag
- tagcloud
- archive
#- recent_comments
- links
- friend_links

## Img cdn path for Links
#cdn_url: https://hexo-ali.oss-cn-beijing.aliyuncs.com/
banner_img: banner.png
footer_img: footer.jpg

## Links
links:
    github-alt: https://github.com/hiphopcoders
    zhihu: 
    weixin: weixin.png
    qq: qq.png
    weibo: 
    csdn: 
    qqmusic: 
    neteasemusic: 
    envelope-o: mailto:hiphopcoder@163.com
    music:
    douban:
    facebook:
    linkedin:
    twitter:

# Friend_links
friend_links:
    简眸: https://jianmou.github.io


# Miscellaneous
favicon: favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Baidu share
baidushare: true

#是否开启打赏功能
donate: true
#打赏文案
Alipay: Alipay.jpg
WeChatpay: WeChatpay.jpg
donate_message: 欣赏此文？求鼓励，求支持！


### 插件配置
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# hexo-deployer-git (https://github.com/hexojs/hexo-deployer-git)
deploy:
  - type: git
    repo: 你的部署仓库地址
    branch: 你部署分支
  
# hexo-plugin-gitalk (https://github.com/snowdreams1006/hexo-plugin-gitalk)
gitalk:
  clientID: ''
  clientSecret: ''
  repo: 
  owner: 
  admin: 
  distractionFreeMode: false

# hexo-generator-feed (https://github.com/hexojs/hexo-generator-feed)
feed:
  type:
    - atom
    - rss2

# hexo-admonition (https://github.com/lxl80/hexo-admonition)
#  note
#  info, todo
#  warning, attention, caution
#  error, failure, missing, fail

# hexo-algolia (https://github.com/oncletom/hexo-algolia)
algolia:
  applicationID: ''
  apiKey: ''
  adminApiKey: ''
  indexName: ''
  chunkSize: 5000

# hexo-auto-excerpt (https://github.com/ashisherc/hexo-auto-excerpt)
excerpt_length: 500

# hexo-addlin (https://github.com/acwong00/hexo-addlink)
addlink:
  before_text: <div class="copyright">作者：卡尔西  </br><span>本文地址：
  after_text: </span></br> 如果本文对你有帮助，欢迎微信,QQ联系,复制转载请注明作者和原文链接，谢谢!</br> 但管努力，莫问前程，事在人为，功不唐捐 ~  </div>

# hexo-easy-tags-plugin (https://github.com/dailyrandomphoto/hexo-easy-tags-plugin)
easy_tags_plugin:
  enable: true
  tag_name_case: 1
  sort_ignore_case: true

# hexo-abbrlink(https://github.com/rozbo/hexo-abbrlink)
abbrlink:
  alg: crc32
  rep: hex


### 推广分析配置
# Baidu Analytics ID
baidu_analytics: 
baidu_site_verification: 

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
# Google Analytics
google_analytics: 
google_site_verification: 

#qihu verification setting
qihu_site_verification: 

# bing verification setting
bing_site_verification: 


